export const CURRENCIES: { code: string; name: string; symbol: string; zeroDecimal: boolean }[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', zeroDecimal: false },
  { code: 'EUR', name: 'Euro', symbol: '€', zeroDecimal: false },
  { code: 'GBP', name: 'British Pound', symbol: '£', zeroDecimal: false },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', zeroDecimal: true },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', zeroDecimal: false },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', zeroDecimal: false },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', zeroDecimal: false },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', zeroDecimal: false },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', zeroDecimal: false },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', zeroDecimal: false },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', zeroDecimal: false },
  { code: 'AED', name: 'UAE Dirham', symbol: 'AED', zeroDecimal: false },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', zeroDecimal: false },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', zeroDecimal: false },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', zeroDecimal: true },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', zeroDecimal: false },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', zeroDecimal: false },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', zeroDecimal: false },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', zeroDecimal: false },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', zeroDecimal: false },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', zeroDecimal: false },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', zeroDecimal: false },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', zeroDecimal: false },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', zeroDecimal: false },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', zeroDecimal: false },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', zeroDecimal: false },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', zeroDecimal: true },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', zeroDecimal: false },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', zeroDecimal: false },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', zeroDecimal: false },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', zeroDecimal: false },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', zeroDecimal: false },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QR', zeroDecimal: false },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', zeroDecimal: false },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', zeroDecimal: false },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', zeroDecimal: false },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', zeroDecimal: true },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', zeroDecimal: true },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', zeroDecimal: true },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', zeroDecimal: false },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', zeroDecimal: false },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', zeroDecimal: false },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', zeroDecimal: false },
];

export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'BE', name: 'Belgium' },
  { code: 'IE', name: 'Ireland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'DK', name: 'Denmark' },
  { code: 'FI', name: 'Finland' },
  { code: 'PL', name: 'Poland' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'HU', name: 'Hungary' },
  { code: 'RO', name: 'Romania' },
  { code: 'GR', name: 'Greece' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'AT', name: 'Austria' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'South Korea' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'India' },
  { code: 'SG', name: 'Singapore' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'PH', name: 'Philippines' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'QA', name: 'Qatar' },
  { code: 'IL', name: 'Israel' },
  { code: 'TR', name: 'Turkey' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenya' },
  { code: 'GH', name: 'Ghana' },
  { code: 'EG', name: 'Egypt' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'PE', name: 'Peru' },
  { code: 'CA', name: 'Canada' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'RU', name: 'Russia' },
];

export const PAYMENT_METHODS = [
  { value: 'card', label: 'Card' },
  { value: 'bank_transfer', label: 'Bank Transfer' },
  { value: 'wallet', label: 'Digital Wallet' },
  { value: 'upi', label: 'UPI' },
  { value: 'paypal', label: 'PayPal' },
  { value: 'crypto', label: 'Cryptocurrency' },
];

export const PAYOUT_SCHEDULES = [
  { value: 'manual', label: 'Manual' },
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
];

export const REFUND_REASONS = [
  { value: 'duplicate', label: 'Duplicate payment' },
  { value: 'fraudulent', label: 'Fraudulent transaction' },
  { value: 'customer_request', label: 'Customer requested' },
  { value: 'service_issue', label: 'Service or product issue' },
  { value: 'other', label: 'Other' },
];
