import type { Vehicle, Destination, Airport, Hotel } from "./types";

export const VEHICLES: Vehicle[] = [
  {
    id: "economy-sedan",
    name: "Economy Sedan",
    class: "economy",
    image: "https://images.pexels.com/photos/28673504/pexels-photo-28673504.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 3,
    luggage: 2,
    doors: 4,
    basePriceUSD: 35,
    description: "Comfortable and efficient for solo travelers and couples. Perfect for city-to-airport transfers.",
    features: ["Air conditioning", "Free Wi-Fi", "Professional driver", "Bottled water"],
    transferMultiplier: 1,
    carHireDailyMultiplier: 42,
    parkingDailyUSD: 8,
  },
  {
    id: "executive-sedan",
    name: "Executive Sedan",
    class: "executive",
    image: "https://images.pexels.com/photos/14764071/pexels-photo-14764071.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 3,
    luggage: 3,
    doors: 4,
    basePriceUSD: 65,
    description: "Premium sedan for business travelers. Leather interiors and a smooth, quiet ride.",
    features: ["Leather seats", "Free Wi-Fi", "Phone chargers", "Bottled water", "Meet & greet"],
    transferMultiplier: 1.6,
    carHireDailyMultiplier: 78,
    parkingDailyUSD: 12,
  },
  {
    id: "luxury-mercedes",
    name: "Luxury Mercedes S-Class",
    class: "luxury",
    image: "https://images.pexels.com/photos/26691312/pexels-photo-26691312.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 3,
    luggage: 3,
    doors: 4,
    basePriceUSD: 120,
    description: "Top-tier luxury for VIPs and special occasions. Chauffeur-driven Mercedes S-Class.",
    features: ["Premium leather", "Free Wi-Fi", "Champine service", "Climate control", "Meet & greet", "Flight tracking"],
    transferMultiplier: 2.8,
    carHireDailyMultiplier: 145,
    parkingDailyUSD: 18,
  },
  {
    id: "suv-prado",
    name: "Premium SUV",
    class: "suv",
    image: "https://images.pexels.com/photos/18029607/pexels-photo-18029607.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 5,
    luggage: 4,
    doors: 5,
    basePriceUSD: 85,
    description: "Spacious SUV for families and groups. Extra luggage capacity and elevated seating.",
    features: ["Air conditioning", "Free Wi-Fi", "Large trunk", "Phone chargers", "Bottled water"],
    transferMultiplier: 2.1,
    carHireDailyMultiplier: 98,
    parkingDailyUSD: 14,
  },
  {
    id: "van-class",
    name: "Mercedes V-Class Van",
    class: "van",
    image: "https://images.pexels.com/photos/17455633/pexels-photo-17455633.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 7,
    luggage: 7,
    doors: 5,
    basePriceUSD: 110,
    description: "Perfect for larger groups and families. Comfortable seating for up to 7 passengers.",
    features: ["7 seats", "Free Wi-Fi", "Extra luggage", "Phone chargers", "Bottled water", "Meet & greet"],
    transferMultiplier: 2.6,
    carHireDailyMultiplier: 125,
    parkingDailyUSD: 16,
  },
  {
    id: "minibus-coach",
    name: "Minibus Coach",
    class: "minibus",
    image: "https://images.pexels.com/photos/19069436/pexels-photo-19069436.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 16,
    luggage: 16,
    doors: 4,
    basePriceUSD: 180,
    description: "For large groups and corporate travel. Seats up to 16 with ample luggage space.",
    features: ["16 seats", "Free Wi-Fi", "Luggage trailer", "PA system", "Air conditioning", "Phone chargers"],
    transferMultiplier: 4.2,
    carHireDailyMultiplier: 210,
    parkingDailyUSD: 22,
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "london",
    city: "London",
    country: "United Kingdom",
    airportCode: "LHR",
    airportName: "Heathrow Airport",
    image: "https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "UAE",
    airportCode: "DXB",
    airportName: "Dubai International Airport",
    image: "https://images.pexels.com/photos/823696/pexels-photo-823696.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "newyork",
    city: "New York",
    country: "USA",
    airportCode: "JFK",
    airportName: "John F. Kennedy International",
    image: "https://images.pexels.com/photos/802024/pexels-photo-802024.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "paris",
    city: "Paris",
    country: "France",
    airportCode: "CDG",
    airportName: "Charles de Gaulle Airport",
    image: "https://images.pexels.com/photos/161853/eiffel-tower-paris-eiffel-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "tokyo",
    city: "Tokyo",
    country: "Japan",
    airportCode: "NRT",
    airportName: "Narita International Airport",
    image: "https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "singapore",
    city: "Singapore",
    country: "Singapore",
    airportCode: "SIN",
    airportName: "Changi Airport",
    image: "https://images.pexels.com/photos/8190152/pexels-photo-8190152.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "sydney",
    city: "Sydney",
    country: "Australia",
    airportCode: "SYD",
    airportName: "Sydney Kingsford Smith",
    image: "https://images.pexels.com/photos/994605/pexels-photo-994605.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "mumbai",
    city: "Mumbai",
    country: "India",
    airportCode: "BOM",
    airportName: "Chhatrapati Shivaji International",
    image: "https://images.pexels.com/photos/3592343/pexels-photo-3592343.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "istanbul",
    city: "Istanbul",
    country: "Turkey",
    airportCode: "IST",
    airportName: "Istanbul Airport",
    image: "https://images.pexels.com/photos/1549326/pexels-photo-1549326.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "bangkok",
    city: "Bangkok",
    country: "Thailand",
    airportCode: "BKK",
    airportName: "Suvarnabhumi Airport",
    image: "https://images.pexels.com/photos/1031659/pexels-photo-1031659.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    airportCode: "AMS",
    airportName: "Schiphol Airport",
    image: "https://images.pexels.com/photos/1796715/pexels-photo-1796715.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "capetown",
    city: "Cape Town",
    country: "South Africa",
    airportCode: "CPT",
    airportName: "Cape Town International",
    image: "https://images.pexels.com/photos/934718/pexels-photo-934718.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
];

const BASE_AIRPORT_LIST: Airport[] = [
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom" },
  { code: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom" },
  { code: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom" },
  { code: "LTN", name: "Luton Airport", city: "London", country: "United Kingdom" },
  { code: "LCY", name: "London City Airport", city: "London", country: "United Kingdom" },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { code: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom" },
  { code: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom" },
  { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
  { code: "DWC", name: "Al Maktoum International Airport", city: "Dubai", country: "UAE" },
  { code: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "UAE" },
  { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
  { code: "JFK", name: "John F. Kennedy International", city: "New York", country: "USA" },
  { code: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA" },
  { code: "EWR", name: "Newark Liberty International", city: "New York", country: "USA" },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "USA" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", country: "USA" },
  { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
  { code: "MIA", name: "Miami International Airport", city: "Miami", country: "USA" },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta", city: "Atlanta", country: "USA" },
  { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "USA" },
  { code: "BOS", name: "Logan International Airport", city: "Boston", country: "USA" },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "USA" },
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada" },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada" },
  { code: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "Canada" },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
  { code: "ORY", name: "Orly Airport", city: "Paris", country: "France" },
  { code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany" },
  { code: "AMS", name: "Schiphol Airport", city: "Amsterdam", country: "Netherlands" },
  { code: "FCO", name: "Fiumicino Airport", city: "Rome", country: "Italy" },
  { code: "MXP", name: "Malpensa Airport", city: "Milan", country: "Italy" },
  { code: "VCE", name: "Marco Polo Airport", city: "Venice", country: "Italy" },
  { code: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "Spain" },
  { code: "BCN", name: "Barcelona-El Prat Airport", city: "Barcelona", country: "Spain" },
  { code: "AGP", name: "Málaga-Costa del Sol Airport", city: "Malaga", country: "Spain" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { code: "SAW", name: "Sabiha Gökçen Airport", city: "Istanbul", country: "Turkey" },
  { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
  { code: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan" },
  { code: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan" },
  { code: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore" },
  { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { code: "DMK", name: "Don Mueang Airport", city: "Bangkok", country: "Thailand" },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia" },
  { code: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia" },
  { code: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines" },
  { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
  { code: "TPE", name: "Taoyuan International Airport", city: "Taipei", country: "Taiwan" },
  { code: "PEK", name: "Beijing Capital International", city: "Beijing", country: "China" },
  { code: "PVG", name: "Pudong International Airport", city: "Shanghai", country: "China" },
  { code: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "China" },
  { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { code: "BOM", name: "Chhatrapati Shivaji International", city: "Mumbai", country: "India" },
  { code: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "India" },
  { code: "BLR", name: "Kempegowda International", city: "Bangalore", country: "India" },
  { code: "MAA", name: "Chennai International", city: "Chennai", country: "India" },
  { code: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose", city: "Kolkata", country: "India" },
  { code: "COK", name: "Cochin International", city: "Kochi", country: "India" },
  { code: "GOI", name: "Goa Dabolim Airport", city: "Goa", country: "India" },
  { code: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa" },
  { code: "JNB", name: "O.R. Tambo International", city: "Johannesburg", country: "South Africa" },
  { code: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya" },
  { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
  { code: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco" },
  { code: "GRU", name: "São Paulo-Guarulhos International", city: "São Paulo", country: "Brazil" },
  { code: "GIG", name: "Rio de Janeiro-Galeão", city: "Rio de Janeiro", country: "Brazil" },
  { code: "EZE", name: "Ministro Pistarini Airport", city: "Buenos Aires", country: "Argentina" },
  { code: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia" },
  { code: "MEX", name: "Mexico City International", city: "Mexico City", country: "Mexico" },
  { code: "CUN", name: "Cancún International", city: "Cancún", country: "Mexico" },
  { code: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
  { code: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
  { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
  { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
  { code: "OSL", name: "Oslo Airport Gardermoen", city: "Oslo", country: "Norway" },
  { code: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "Finland" },
  { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
  { code: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
  { code: "BUD", name: "Budapest Ferenc Liszt", city: "Budapest", country: "Hungary" },
  { code: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "Russia" },
  { code: "DME", name: "Domodedovo International", city: "Moscow", country: "Russia" },
  { code: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel" },
  { code: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia" },
  { code: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia" },
  { code: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica" },
  { code: "PAP", name: "Toussaint Louverture Airport", city: "Port-au-Prince", country: "Haiti" },
];


// Expanded European airport coverage. The search is code/city/name aware, so customers
// can type an IATA code, airport name, city or country and still find the airport.
const EUROPEAN_AIRPORTS: Airport[] = [
  { code: "BFS", name: "Belfast International Airport", city: "Belfast", country: "United Kingdom" },
  { code: "BHD", name: "George Best Belfast City Airport", city: "Belfast", country: "United Kingdom" },
  { code: "BRS", name: "Bristol Airport", city: "Bristol", country: "United Kingdom" },
  { code: "LPL", name: "Liverpool John Lennon Airport", city: "Liverpool", country: "United Kingdom" },
  { code: "NCL", name: "Newcastle International Airport", city: "Newcastle", country: "United Kingdom" },
  { code: "EMA", name: "East Midlands Airport", city: "Nottingham", country: "United Kingdom" },
  { code: "ABZ", name: "Aberdeen Airport", city: "Aberdeen", country: "United Kingdom" },
  { code: "SOU", name: "Southampton Airport", city: "Southampton", country: "United Kingdom" },
  { code: "EXT", name: "Exeter Airport", city: "Exeter", country: "United Kingdom" },
  { code: "CWL", name: "Cardiff Airport", city: "Cardiff", country: "United Kingdom" },
  { code: "JER", name: "Jersey Airport", city: "Saint Helier", country: "United Kingdom" },
  { code: "GCI", name: "Guernsey Airport", city: "Saint Peter Port", country: "United Kingdom" },
  { code: "ADB", name: "İzmir Adnan Menderes Airport", city: "Izmir", country: "Turkey" },
  { code: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey" },
  { code: "DLM", name: "Dalaman Airport", city: "Dalaman", country: "Turkey" },
  { code: "ESB", name: "Ankara Esenboğa Airport", city: "Ankara", country: "Turkey" },
  { code: "BJV", name: "Milas-Bodrum Airport", city: "Bodrum", country: "Turkey" },
  { code: "PRN", name: "Pristina International Airport", city: "Pristina", country: "Kosovo" },
  { code: "ZTH", name: "Zakynthos International Airport", city: "Zakynthos", country: "Greece" },
  { code: "KGS", name: "Kos Airport", city: "Kos", country: "Greece" },
  { code: "MJT", name: "Mytilene International Airport", city: "Mytilene", country: "Greece" },
  { code: "KVA", name: "Kavala International Airport", city: "Kavala", country: "Greece" },
  { code: "LPA", name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain" },
  { code: "FUE", name: "Fuerteventura Airport", city: "Fuerteventura", country: "Spain" },
  { code: "ACE", name: "Lanzarote Airport", city: "Lanzarote", country: "Spain" },
  { code: "REU", name: "Reus Airport", city: "Reus", country: "Spain" },
  { code: "GRO", name: "Girona-Costa Brava Airport", city: "Girona", country: "Spain" },
  { code: "SDR", name: "Santander Airport", city: "Santander", country: "Spain" },
  { code: "SCQ", name: "Santiago-Rosalía de Castro Airport", city: "Santiago de Compostela", country: "Spain" },
  { code: "VGO", name: "Vigo Airport", city: "Vigo", country: "Spain" },
  { code: "GRX", name: "Federico García Lorca Granada Airport", city: "Granada", country: "Spain" },
  { code: "RNS", name: "Rennes–Saint-Jacques Airport", city: "Rennes", country: "France" },
  { code: "CFE", name: "Clermont-Ferrand Auvergne Airport", city: "Clermont-Ferrand", country: "France" },
  { code: "ETZ", name: "Metz-Nancy-Lorraine Airport", city: "Metz", country: "France" },
  { code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
  { code: "FMO", name: "Münster Osnabrück Airport", city: "Münster", country: "Germany" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { code: "LEJ", name: "Leipzig/Halle Airport", city: "Leipzig", country: "Germany" },
  { code: "SXF", name: "Berlin Schönefeld Airport", city: "Berlin", country: "Germany" },
  { code: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy" },
  { code: "GOA", name: "Genoa Cristoforo Colombo Airport", city: "Genoa", country: "Italy" },
  { code: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy" },
  { code: "AOI", name: "Ancona Falconara Airport", city: "Ancona", country: "Italy" },
  { code: "TSF", name: "Treviso Airport", city: "Treviso", country: "Italy" },
  { code: "LEI", name: "Almería Airport", city: "Almeria", country: "Spain" },
  { code: "KLU", name: "Klagenfurt Airport", city: "Klagenfurt", country: "Austria" },
  { code: "LNZ", name: "Linz Airport", city: "Linz", country: "Austria" },
  { code: "AAR", name: "Aarhus Airport", city: "Aarhus", country: "Denmark" },
  { code: "BLL", name: "Billund Airport", city: "Billund", country: "Denmark" },
  { code: "TOS", name: "Tromsø Airport", city: "Tromso", country: "Norway" },
  { code: "SVG", name: "Stavanger Airport", city: "Stavanger", country: "Norway" },
  { code: "AES", name: "Ålesund Airport", city: "Alesund", country: "Norway" },
  { code: "UME", name: "Umeå Airport", city: "Umea", country: "Sweden" },
  { code: "MMX", name: "Malmö Airport", city: "Malmo", country: "Sweden" },
  { code: "LNZ", name: "Linz Airport", city: "Linz", country: "Austria" },
  { code: "SJJ", name: "Sarajevo International Airport", city: "Sarajevo", country: "Bosnia and Herzegovina" },
  { code: "OMO", name: "Mostar Airport", city: "Mostar", country: "Bosnia and Herzegovina" },
  { code: "SKP", name: "Skopje International Airport", city: "Skopje", country: "North Macedonia" },
  { code: "OHD", name: "Ohrid St. Paul the Apostle Airport", city: "Ohrid", country: "North Macedonia" },

  { code: "TIA", name: "Tirana International Airport", city: "Tirana", country: "Albania" },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { code: "CRL", name: "Brussels South Charleroi Airport", city: "Charleroi", country: "Belgium" },
  { code: "ANR", name: "Antwerp International Airport", city: "Antwerp", country: "Belgium" },
  { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
  { code: "BOJ", name: "Burgas Airport", city: "Burgas", country: "Bulgaria" },
  { code: "VAR", name: "Varna Airport", city: "Varna", country: "Bulgaria" },
  { code: "ZAG", name: "Zagreb Franjo Tuđman Airport", city: "Zagreb", country: "Croatia" },
  { code: "SPU", name: "Split Airport", city: "Split", country: "Croatia" },
  { code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia" },
  { code: "ZAD", name: "Zadar Airport", city: "Zadar", country: "Croatia" },
  { code: "PUY", name: "Pula Airport", city: "Pula", country: "Croatia" },
  { code: "LCA", name: "Larnaca International Airport", city: "Larnaca", country: "Cyprus" },
  { code: "PFO", name: "Paphos International Airport", city: "Paphos", country: "Cyprus" },
  { code: "TLL", name: "Tallinn Airport", city: "Tallinn", country: "Estonia" },
  { code: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "Finland" },
  { code: "TMP", name: "Tampere-Pirkkala Airport", city: "Tampere", country: "Finland" },
  { code: "BOD", name: "Bordeaux-Mérignac Airport", city: "Bordeaux", country: "France" },
  { code: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "France" },
  { code: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France" },
  { code: "TLS", name: "Toulouse-Blagnac Airport", city: "Toulouse", country: "France" },
  { code: "NTE", name: "Nantes Atlantique Airport", city: "Nantes", country: "France" },
  { code: "LIL", name: "Lille Airport", city: "Lille", country: "France" },
  { code: "MPL", name: "Montpellier-Méditerranée Airport", city: "Montpellier", country: "France" },
  { code: "BIA", name: "Bastia-Poretta Airport", city: "Bastia", country: "France" },
  { code: "BES", name: "Brest Bretagne Airport", city: "Brest", country: "France" },
  { code: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany" },
  { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  { code: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany" },
  { code: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany" },
  { code: "HAJ", name: "Hannover Airport", city: "Hannover", country: "Germany" },
  { code: "NUE", name: "Nuremberg Airport", city: "Nuremberg", country: "Germany" },
  { code: "DRS", name: "Dresden Airport", city: "Dresden", country: "Germany" },
  { code: "SKG", name: "Thessaloniki Airport", city: "Thessaloniki", country: "Greece" },
  { code: "HER", name: "Heraklion International Airport", city: "Heraklion", country: "Greece" },
  { code: "RHO", name: "Rhodes International Airport", city: "Rhodes", country: "Greece" },
  { code: "CFU", name: "Corfu International Airport", city: "Corfu", country: "Greece" },
  { code: "JTR", name: "Santorini Airport", city: "Santorini", country: "Greece" },
  { code: "CHQ", name: "Chania International Airport", city: "Chania", country: "Greece" },
  { code: "KEF", name: "Keflavík International Airport", city: "Reykjavik", country: "Iceland" },
  { code: "ORK", name: "Cork Airport", city: "Cork", country: "Ireland" },
  { code: "SNN", name: "Shannon Airport", city: "Shannon", country: "Ireland" },
  { code: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy" },
  { code: "BLQ", name: "Bologna Guglielmo Marconi Airport", city: "Bologna", country: "Italy" },
  { code: "PSA", name: "Pisa International Airport", city: "Pisa", country: "Italy" },
  { code: "PMO", name: "Palermo Airport", city: "Palermo", country: "Italy" },
  { code: "CTA", name: "Catania Airport", city: "Catania", country: "Italy" },
  { code: "CAG", name: "Cagliari Elmas Airport", city: "Cagliari", country: "Italy" },
  { code: "BRI", name: "Bari Karol Wojtyła Airport", city: "Bari", country: "Italy" },
  { code: "TRN", name: "Turin Airport", city: "Turin", country: "Italy" },
  { code: "FLR", name: "Florence Airport", city: "Florence", country: "Italy" },
  { code: "VRN", name: "Verona Villafranca Airport", city: "Verona", country: "Italy" },
  { code: "BGY", name: "Milan Bergamo Airport", city: "Bergamo", country: "Italy" },
  { code: "RIX", name: "Riga International Airport", city: "Riga", country: "Latvia" },
  { code: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania" },
  { code: "KUN", name: "Kaunas Airport", city: "Kaunas", country: "Lithuania" },
  { code: "LUX", name: "Luxembourg Airport", city: "Luxembourg", country: "Luxembourg" },
  { code: "MLA", name: "Malta International Airport", city: "Valletta", country: "Malta" },
  { code: "TGD", name: "Podgorica Airport", city: "Podgorica", country: "Montenegro" },
  { code: "TIV", name: "Tivat Airport", city: "Tivat", country: "Montenegro" },
  { code: "AMS", name: "Schiphol Airport", city: "Amsterdam", country: "Netherlands" },
  { code: "EIN", name: "Eindhoven Airport", city: "Eindhoven", country: "Netherlands" },
  { code: "RTM", name: "Rotterdam The Hague Airport", city: "Rotterdam", country: "Netherlands" },
  { code: "BGO", name: "Bergen Airport Flesland", city: "Bergen", country: "Norway" },
  { code: "TRD", name: "Trondheim Airport Værnes", city: "Trondheim", country: "Norway" },
  { code: "WRO", name: "Wrocław Airport", city: "Wroclaw", country: "Poland" },
  { code: "KRK", name: "John Paul II Kraków Airport", city: "Krakow", country: "Poland" },
  { code: "GDN", name: "Gdańsk Lech Wałęsa Airport", city: "Gdansk", country: "Poland" },
  { code: "KTW", name: "Katowice Airport", city: "Katowice", country: "Poland" },
  { code: "POZ", name: "Poznań Airport", city: "Poznan", country: "Poland" },
  { code: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
  { code: "OPO", name: "Francisco Sá Carneiro Airport", city: "Porto", country: "Portugal" },
  { code: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal" },
  { code: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania" },
  { code: "CLJ", name: "Cluj-Napoca International Airport", city: "Cluj-Napoca", country: "Romania" },
  { code: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia" },
  { code: "BTS", name: "Bratislava Airport", city: "Bratislava", country: "Slovakia" },
  { code: "LJU", name: "Ljubljana Jože Pučnik Airport", city: "Ljubljana", country: "Slovenia" },
  { code: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain" },
  { code: "PMI", name: "Palma de Mallorca Airport", city: "Palma", country: "Spain" },
  { code: "TFS", name: "Tenerife South Airport", city: "Tenerife", country: "Spain" },
  { code: "LPA", name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain" },
  { code: "ALC", name: "Alicante-Elche Airport", city: "Alicante", country: "Spain" },
  { code: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "Spain" },
  { code: "BIO", name: "Bilbao Airport", city: "Bilbao", country: "Spain" },
  { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain" },
  { code: "GOT", name: "Göteborg Landvetter Airport", city: "Gothenburg", country: "Sweden" },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { code: "BSL", name: "EuroAirport Basel-Mulhouse-Freiburg", city: "Basel", country: "Switzerland" },
  { code: "SZG", name: "Salzburg Airport", city: "Salzburg", country: "Austria" },
  { code: "GRZ", name: "Graz Airport", city: "Graz", country: "Austria" },
  { code: "INN", name: "Innsbruck Airport", city: "Innsbruck", country: "Austria" },
  { code: "SVO", name: "Sheremetyevo International Airport", city: "Moscow", country: "Russia" },
  { code: "DME", name: "Domodedovo International Airport", city: "Moscow", country: "Russia" },
  { code: "LED", name: "Pulkovo Airport", city: "Saint Petersburg", country: "Russia" },
  { code: "KBP", name: "Boryspil International Airport", city: "Kyiv", country: "Ukraine" },
  { code: "KIV", name: "Chișinău International Airport", city: "Chisinau", country: "Moldova" },
  { code: "TBS", name: "Tbilisi International Airport", city: "Tbilisi", country: "Georgia" },
  { code: "EVN", name: "Zvartnots International Airport", city: "Yerevan", country: "Armenia" },
  { code: "BAK", name: "Heydar Aliyev International Airport", city: "Baku", country: "Azerbaijan" },
];

export const AIRPORT_LIST: Airport[] = Array.from(
  new Map([...BASE_AIRPORT_LIST, ...EUROPEAN_AIRPORTS].map((airport) => [airport.code, airport])).values()
);

export const HOTELS_BY_CITY: Record<string, Hotel[]> = {
  London: [
    { id: "lon-1", name: "The Savoy", area: "Strand, Central London", city: "London" },
    { id: "lon-2", name: "The Ritz London", area: "Piccadilly, Mayfair", city: "London" },
    { id: "lon-3", name: "Shangri-La at The Shard", area: "London Bridge", city: "London" },
    { id: "lon-4", name: "Park Plaza Westminster Bridge", area: "Waterloo, South Bank", city: "London" },
    { id: "lon-5", name: "Hilton London Metropole", area: "Paddington, Central London", city: "London" },
    { id: "lon-6", name: "The Langham", area: "Portland Place, Regent's Park", city: "London" },
    { id: "lon-7", name: "InterContinental Park Lane", area: "Mayfair, Central London", city: "London" },
    { id: "lon-8", name: "Premier Inn County Hall", area: "South Bank, Waterloo", city: "London" },
  ],
  Dubai: [
    { id: "dxb-1", name: "Burj Al Arab Jumeirah", area: "Jumeirah Beach", city: "Dubai" },
    { id: "dxb-2", name: "Atlantis The Palm", area: "Palm Jumeirah", city: "Dubai" },
    { id: "dxb-3", name: "Armani Hotel Dubai", area: "Downtown Dubai, Burj Khalifa", city: "Dubai" },
    { id: "dxb-4", name: "JW Marriott Marquis Dubai", area: "Business Bay", city: "Dubai" },
    { id: "dxb-5", name: "Raffles Dubai", area: "Wafi City, Oud Metha", city: "Dubai" },
    { id: "dxb-6", name: "Four Seasons Resort DIFC", area: "DIFC, Financial Centre", city: "Dubai" },
    { id: "dxb-7", name: "Hyatt Regency Dubai", area: "Deira Corniche", city: "Dubai" },
    { id: "dxb-8", name: "Jumeirah Beach Hotel", area: "Jumeirah Beach Residence", city: "Dubai" },
  ],
  "New York": [
    { id: "nyc-1", name: "The Plaza Hotel", area: "5th Avenue, Midtown Manhattan", city: "New York" },
    { id: "nyc-2", name: "Four Seasons New York", area: "57th Street, Midtown", city: "New York" },
    { id: "nyc-3", name: "The Ritz-Carlton New York", area: "Central Park South", city: "New York" },
    { id: "nyc-4", name: "Marriott Marquis Times Square", area: "Times Square, Midtown", city: "New York" },
    { id: "nyc-5", name: "Hilton New York Midtown", area: "53rd Street, Midtown", city: "New York" },
    { id: "nyc-6", name: "1 Hotel Brooklyn Bridge", area: "Brooklyn Bridge Park", city: "New York" },
    { id: "nyc-7", name: "The Standard High Line", area: "Meatpacking District", city: "New York" },
    { id: "nyc-8", name: "Hyatt Grand Central New York", area: "42nd Street, Midtown", city: "New York" },
  ],
  Paris: [
    { id: "par-1", name: "Hôtel de Crillon", area: "Place de la Concorde, 1st Arr.", city: "Paris" },
    { id: "par-2", name: "The Ritz Paris", area: "Place Vendôme, 1st Arr.", city: "Paris" },
    { id: "par-3", name: "Le Meurice", area: "Rue de Rivoli, 1st Arr.", city: "Paris" },
    { id: "par-4", name: "Hilton Paris Opera", area: "Gare Saint-Lazare, 8th Arr.", city: "Paris" },
    { id: "par-5", name: "Pullman Paris Tour Eiffel", area: "Near Eiffel Tower, 15th Arr.", city: "Paris" },
    { id: "par-6", name: "Marriott Champs-Élysées", area: "Champs-Élysées, 8th Arr.", city: "Paris" },
    { id: "par-7", name: "Hotel Lutetia", area: "Saint-Germain-des-Prés, 6th Arr.", city: "Paris" },
    { id: "par-8", name: "Novotel Paris Les Halles", area: "Les Halles, 1st Arr.", city: "Paris" },
  ],
  Tokyo: [
    { id: "tyo-1", name: "The Peninsula Tokyo", area: "Marunouchi, Chiyoda", city: "Tokyo" },
    { id: "tyo-2", name: "Park Hyatt Tokyo", area: "Shinjuku", city: "Tokyo" },
    { id: "tyo-3", name: "Four Seasons Hotel Tokyo", area: "Otemachi", city: "Tokyo" },
    { id: "tyo-4", name: "Imperial Hotel Tokyo", area: "Hibiya, Chiyoda", city: "Tokyo" },
    { id: "tyo-5", name: "Hilton Tokyo Bay", area: "Tokyo Disney Resort, Urayasu", city: "Tokyo" },
    { id: "tyo-6", name: "Mandarin Oriental Tokyo", area: "Nihonbashi Muromachi", city: "Tokyo" },
    { id: "tyo-7", name: "Grand Hyatt Tokyo", area: "Roppongi Hills, Minato", city: "Tokyo" },
    { id: "tyo-8", name: "Shinjuku Prince Hotel", area: "Shinjuku", city: "Tokyo" },
  ],
  Singapore: [
    { id: "sin-1", name: "Marina Bay Sands", area: "Marina Bay", city: "Singapore" },
    { id: "sin-2", name: "Raffles Singapore", area: "Bras Basah Road", city: "Singapore" },
    { id: "sin-3", name: "Mandarin Oriental Singapore", area: "Marina Square", city: "Singapore" },
    { id: "sin-4", name: "Shangri-La Singapore", area: "Orchard Road", city: "Singapore" },
    { id: "sin-5", name: "Fullerton Hotel Singapore", area: "Fullerton Square", city: "Singapore" },
    { id: "sin-6", name: "Hilton Singapore Orchard", area: "Orchard Road", city: "Singapore" },
    { id: "sin-7", name: "Capella Singapore", area: "Sentosa Island", city: "Singapore" },
    { id: "sin-8", name: "Swissôtel The Stamford", area: "Raffles City", city: "Singapore" },
  ],
  Sydney: [
    { id: "syd-1", name: "Park Hyatt Sydney", area: "The Rocks, Sydney Harbour", city: "Sydney" },
    { id: "syd-2", name: "Shangri-La Sydney", area: "Cumberland Street, The Rocks", city: "Sydney" },
    { id: "syd-3", name: "Hilton Sydney", area: "George Street, CBD", city: "Sydney" },
    { id: "syd-4", name: "InterContinental Sydney", area: "Macquarie Street, CBD", city: "Sydney" },
    { id: "syd-5", name: "The Langham Sydney", area: "Kent Street, The Rocks", city: "Sydney" },
    { id: "syd-6", name: "Pullman Quay Grand Sydney", area: "Sydney Cove", city: "Sydney" },
  ],
  Mumbai: [
    { id: "bom-1", name: "The Taj Mahal Palace", area: "Apollo Bunder, Colaba", city: "Mumbai" },
    { id: "bom-2", name: "The Oberoi Mumbai", area: "Nariman Point, Marine Drive", city: "Mumbai" },
    { id: "bom-3", name: "Trident Nariman Point", area: "Nariman Point", city: "Mumbai" },
    { id: "bom-4", name: "Four Seasons Hotel Mumbai", area: "Worli", city: "Mumbai" },
    { id: "bom-5", name: "Grand Hyatt Mumbai", area: "BKC, Bandra East", city: "Mumbai" },
    { id: "bom-6", name: "ITC Maratha Mumbai", area: "Andheri East, near Airport", city: "Mumbai" },
    { id: "bom-7", name: "JW Marriott Mumbai Juhu", area: "Juhu Beach", city: "Mumbai" },
    { id: "bom-8", name: "The Leela Mumbai", area: "Andheri East, near Airport", city: "Mumbai" },
  ],
  Istanbul: [
    { id: "ist-1", name: "Çırağan Palace Kempinski", area: "Besiktas, Bosphorus", city: "Istanbul" },
    { id: "ist-2", name: "Four Seasons Bosphorus", area: "Beşiktaş", city: "Istanbul" },
    { id: "ist-3", name: "The Ritz-Carlton Istanbul", area: "Dolmabahçe, Beşiktaş", city: "Istanbul" },
    { id: "ist-4", name: "Hilton Istanbul Bosphorus", area: "Harbiye, Şişli", city: "Istanbul" },
    { id: "ist-5", name: "InterContinental Istanbul", area: "Taksim Square", city: "Istanbul" },
    { id: "ist-6", name: "Swissôtel The Bosphorus", area: "Maçka, Beşiktaş", city: "Istanbul" },
  ],
  Bangkok: [
    { id: "bkk-1", name: "Mandarin Oriental Bangkok", area: "Riverside, Bang Rak", city: "Bangkok" },
    { id: "bkk-2", name: "The Siam Hotel", area: "Riverside, Dusit", city: "Bangkok" },
    { id: "bkk-3", name: "Shangri-La Bangkok", area: "Riverside, Bang Rak", city: "Bangkok" },
    { id: "bkk-4", name: "Hilton Bangkok Millennium", area: "Sukhumvit 18, Khlong Toei", city: "Bangkok" },
    { id: "bkk-5", name: "Grand Hyatt Erawan Bangkok", area: "Ratchadamri, Pathum Wan", city: "Bangkok" },
    { id: "bkk-6", name: "InterContinental Bangkok", area: "Ploenchit, Pathum Wan", city: "Bangkok" },
  ],
  Amsterdam: [
    { id: "ams-1", name: "Hotel Pulitzer Amsterdam", area: "Prinsengracht, Canal Ring", city: "Amsterdam" },
    { id: "ams-2", name: "Conservatorium Hotel", area: "Van Baerlestraat, Museumplein", city: "Amsterdam" },
    { id: "ams-3", name: "Hilton Amsterdam", area: "Apollolaan, Zuid", city: "Amsterdam" },
    { id: "ams-4", name: "InterContinental Amstel", area: "Professor Tulpplein, Riverside", city: "Amsterdam" },
    { id: "ams-5", name: "W Amsterdam", area: "Spuistraat, Central", city: "Amsterdam" },
  ],
  "Cape Town": [
    { id: "cpt-1", name: "One&Only Cape Town", area: "V&A Waterfront", city: "Cape Town" },
    { id: "cpt-2", name: "The Silo Hotel", area: "V&A Waterfront", city: "Cape Town" },
    { id: "cpt-3", name: "Cape Grace Hotel", area: "V&A Waterfront", city: "Cape Town" },
    { id: "cpt-4", name: "Hilton Cape Town City Centre", area: "Buitengracht Street", city: "Cape Town" },
    { id: "cpt-5", name: "Radisson Blu Hotel Waterfront", area: "Granger Bay", city: "Cape Town" },
  ],
};

export function getHotelsForCity(city: string): Hotel[] {
  return HOTELS_BY_CITY[city] || [];
}

export function getHotelsForAirport(airportCode: string): Hotel[] {
  const airport = AIRPORT_LIST.find((a) => a.code === airportCode);
  if (!airport) return [];
  return getHotelsForCity(airport.city);
}

export function getAirportByCode(code: string): Airport | undefined {
  return AIRPORT_LIST.find((airport) => airport.code.toUpperCase() === code.toUpperCase());
}

export function getAirportsForCity(city: string): Airport[] {
  return AIRPORT_LIST.filter((airport) => airport.city.toLowerCase() === city.toLowerCase());
}

export function getAirportFromLocation(location: string): Airport | undefined {
  const value = location.trim().toLowerCase();
  if (!value) return undefined;
  const code = value.split(" - ")[0].trim().toUpperCase();
  return (
    getAirportByCode(code) ||
    AIRPORT_LIST.find((airport) =>
      airport.name.toLowerCase() === value ||
      airport.city.toLowerCase() === value ||
      airport.code.toLowerCase() === value ||
      `${airport.name}, ${airport.city}`.toLowerCase() === value
    )
  );
}

export function getLocalCurrencyForCountry(country: string): string {
  const map: Record<string, string> = {
    "United Kingdom": "GBP", "France": "EUR", "Germany": "EUR", "Spain": "EUR",
    "Italy": "EUR", "Netherlands": "EUR", "Belgium": "EUR", "Austria": "EUR",
    "Ireland": "EUR", "Portugal": "EUR", "Greece": "EUR", "Finland": "EUR",
    "Estonia": "EUR", "Latvia": "EUR", "Lithuania": "EUR", "Luxembourg": "EUR",
    "Malta": "EUR", "Cyprus": "EUR", "Croatia": "EUR", "Slovenia": "EUR",
    "Slovakia": "EUR", "Bulgaria": "BGN", "Czech Republic": "CZK", "Denmark": "DKK",
    "Sweden": "SEK", "Norway": "NOK", "Iceland": "ISK", "Poland": "PLN",
    "Hungary": "HUF", "Romania": "RON", "Switzerland": "CHF", "Turkey": "TRY",
    "Serbia": "RSD", "Albania": "ALL", "North Macedonia": "MKD", "Bosnia and Herzegovina": "BAM",
    "Moldova": "MDL", "Ukraine": "UAH", "Georgia": "GEL", "Russia": "RUB",
    "Armenia": "AMD", "Azerbaijan": "AZN", "UAE": "AED", "Qatar": "QAR",
    "Saudi Arabia": "SAR", "India": "INR", "Japan": "JPY", "Singapore": "SGD",
    "Thailand": "THB", "Australia": "AUD", "Canada": "CAD", "USA": "USD",
    "South Africa": "ZAR", "Egypt": "EGP", "Morocco": "MAD", "Brazil": "BRL",
    "Mexico": "MXN", "New Zealand": "NZD", "Malaysia": "MYR", "Indonesia": "IDR",
    "Philippines": "PHP", "South Korea": "KRW", "Taiwan": "TWD", "China": "CNY",
  };
  return map[country] || "EUR";
}

export const AIRPORT_DATALIST = AIRPORT_LIST.map((a) => ({
  label: `${a.code} - ${a.name}, ${a.city}, ${a.country}`,
  value: `${a.code} - ${a.name}, ${a.city}`,
  code: a.code,
  city: a.city,
}));
