import type { Vehicle, Destination, Airport, Hotel } from "./types";

export const VEHICLES: Vehicle[] = [
  {
    id: "economy-sedan",
    name: "Economy Sedan",
    class: "economy",
    image: "https://images.pexels.com/photos/28673504/pexels-photo-28673504.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 3,
    luggage: 2,
    doors: 4,
    basePriceUSD: 35,
    description: "Comfortable and efficient for solo travelers and couples. Perfect for city-to-airport transfers.",
    features: ["Air conditioning", "Free Wi-Fi", "Professional driver", "Bottled water"],
    transferMultiplier: 1,
    carHireDailyMultiplier: 42,
    parkingDailyUSD: 8,
  },
  {
    id: "executive-sedan",
    name: "Executive Sedan",
    class: "executive",
    image: "https://images.pexels.com/photos/14764071/pexels-photo-14764071.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 3,
    luggage: 3,
    doors: 4,
    basePriceUSD: 65,
    description: "Premium sedan for business travelers. Leather interiors and a smooth, quiet ride.",
    features: ["Leather seats", "Free Wi-Fi", "Phone chargers", "Bottled water", "Meet & greet"],
    transferMultiplier: 1.6,
    carHireDailyMultiplier: 78,
    parkingDailyUSD: 12,
  },
  {
    id: "luxury-mercedes",
    name: "Luxury Mercedes S-Class",
    class: "luxury",
    image: "https://images.pexels.com/photos/26691312/pexels-photo-26691312.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 3,
    luggage: 3,
    doors: 4,
    basePriceUSD: 120,
    description: "Top-tier luxury for VIPs and special occasions. Chauffeur-driven Mercedes S-Class.",
    features: ["Premium leather", "Free Wi-Fi", "Champine service", "Climate control", "Meet & greet", "Flight tracking"],
    transferMultiplier: 2.8,
    carHireDailyMultiplier: 145,
    parkingDailyUSD: 18,
  },
  {
    id: "suv-prado",
    name: "Premium SUV",
    class: "suv",
    image: "https://images.pexels.com/photos/18029607/pexels-photo-18029607.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 5,
    luggage: 4,
    doors: 5,
    basePriceUSD: 85,
    description: "Spacious SUV for families and groups. Extra luggage capacity and elevated seating.",
    features: ["Air conditioning", "Free Wi-Fi", "Large trunk", "Phone chargers", "Bottled water"],
    transferMultiplier: 2.1,
    carHireDailyMultiplier: 98,
    parkingDailyUSD: 14,
  },
  {
    id: "van-class",
    name: "Mercedes V-Class Van",
    class: "van",
    image: "https://images.pexels.com/photos/17455633/pexels-photo-17455633.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 7,
    luggage: 7,
    doors: 5,
    basePriceUSD: 110,
    description: "Perfect for larger groups and families. Comfortable seating for up to 7 passengers.",
    features: ["7 seats", "Free Wi-Fi", "Extra luggage", "Phone chargers", "Bottled water", "Meet & greet"],
    transferMultiplier: 2.6,
    carHireDailyMultiplier: 125,
    parkingDailyUSD: 16,
  },
  {
    id: "minibus-coach",
    name: "Minibus Coach",
    class: "minibus",
    image: "https://images.pexels.com/photos/19069436/pexels-photo-19069436.jpeg?auto=compress&cs=tinysrgb&w=800",
    passengers: 16,
    luggage: 16,
    doors: 4,
    basePriceUSD: 180,
    description: "For large groups and corporate travel. Seats up to 16 with ample luggage space.",
    features: ["16 seats", "Free Wi-Fi", "Luggage trailer", "PA system", "Air conditioning", "Phone chargers"],
    transferMultiplier: 4.2,
    carHireDailyMultiplier: 210,
    parkingDailyUSD: 22,
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "london",
    city: "London",
    country: "United Kingdom",
    airportCode: "LHR",
    airportName: "Heathrow Airport",
    image: "https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "UAE",
    airportCode: "DXB",
    airportName: "Dubai International Airport",
    image: "https://images.pexels.com/photos/823696/pexels-photo-823696.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "newyork",
    city: "New York",
    country: "USA",
    airportCode: "JFK",
    airportName: "John F. Kennedy International",
    image: "https://images.pexels.com/photos/802024/pexels-photo-802024.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "paris",
    city: "Paris",
    country: "France",
    airportCode: "CDG",
    airportName: "Charles de Gaulle Airport",
    image: "https://images.pexels.com/photos/161853/eiffel-tower-paris-eiffel-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "tokyo",
    city: "Tokyo",
    country: "Japan",
    airportCode: "NRT",
    airportName: "Narita International Airport",
    image: "https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "singapore",
    city: "Singapore",
    country: "Singapore",
    airportCode: "SIN",
    airportName: "Changi Airport",
    image: "https://images.pexels.com/photos/8190152/pexels-photo-8190152.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: true,
  },
  {
    id: "sydney",
    city: "Sydney",
    country: "Australia",
    airportCode: "SYD",
    airportName: "Sydney Kingsford Smith",
    image: "https://images.pexels.com/photos/994605/pexels-photo-994605.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "mumbai",
    city: "Mumbai",
    country: "India",
    airportCode: "BOM",
    airportName: "Chhatrapati Shivaji International",
    image: "https://images.pexels.com/photos/3592343/pexels-photo-3592343.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "istanbul",
    city: "Istanbul",
    country: "Turkey",
    airportCode: "IST",
    airportName: "Istanbul Airport",
    image: "https://images.pexels.com/photos/1549326/pexels-photo-1549326.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "bangkok",
    city: "Bangkok",
    country: "Thailand",
    airportCode: "BKK",
    airportName: "Suvarnabhumi Airport",
    image: "https://images.pexels.com/photos/1031659/pexels-photo-1031659.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    airportCode: "AMS",
    airportName: "Schiphol Airport",
    image: "https://images.pexels.com/photos/1796715/pexels-photo-1796715.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
  {
    id: "capetown",
    city: "Cape Town",
    country: "South Africa",
    airportCode: "CPT",
    airportName: "Cape Town International",
    image: "https://images.pexels.com/photos/934718/pexels-photo-934718.jpeg?auto=compress&cs=tinysrgb&w=800",
    popular: false,
  },
];

export const AIRPORT_LIST: Airport[] = [
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom" },
  { code: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom" },
  { code: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom" },
  { code: "LTN", name: "Luton Airport", city: "London", country: "United Kingdom" },
  { code: "LCY", name: "London City Airport", city: "London", country: "United Kingdom" },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { code: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom" },
  { code: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom" },
  { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
  { code: "DWC", name: "Al Maktoum International Airport", city: "Dubai", country: "UAE" },
  { code: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "UAE" },
  { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
  { code: "JFK", name: "John F. Kennedy International", city: "New York", country: "USA" },
  { code: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA" },
  { code: "EWR", name: "Newark Liberty International", city: "New York", country: "USA" },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "USA" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", country: "USA" },
  { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
  { code: "MIA", name: "Miami International Airport", city: "Miami", country: "USA" },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta", city: "Atlanta", country: "USA" },
  { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "USA" },
  { code: "BOS", name: "Logan International Airport", city: "Boston", country: "USA" },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "USA" },
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada" },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada" },
  { code: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "Canada" },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
  { code: "ORY", name: "Orly Airport", city: "Paris", country: "France" },
  { code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany" },
  { code: "AMS", name: "Schiphol Airport", city: "Amsterdam", country: "Netherlands" },
  { code: "FCO", name: "Fiumicino Airport", city: "Rome", country: "Italy" },
  { code: "MXP", name: "Malpensa Airport", city: "Milan", country: "Italy" },
  { code: "VCE", name: "Marco Polo Airport", city: "Venice", country: "Italy" },
  { code: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "Spain" },
  { code: "BCN", name: "Barcelona-El Prat Airport", city: "Barcelona", country: "Spain" },
  { code: "AGP", name: "Málaga-Costa del Sol Airport", city: "Malaga", country: "Spain" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { code: "SAW", name: "Sabiha Gökçen Airport", city: "Istanbul", country: "Turkey" },
  { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
  { code: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan" },
  { code: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan" },
  { code: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore" },
  { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { code: "DMK", name: "Don Mueang Airport", city: "Bangkok", country: "Thailand" },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia" },
  { code: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia" },
  { code: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines" },
  { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
  { code: "TPE", name: "Taoyuan International Airport", city: "Taipei", country: "Taiwan" },
  { code: "PEK", name: "Beijing Capital International", city: "Beijing", country: "China" },
  { code: "PVG", name: "Pudong International Airport", city: "Shanghai", country: "China" },
  { code: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "China" },
  { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { code: "BOM", name: "Chhatrapati Shivaji International", city: "Mumbai", country: "India" },
  { code: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "India" },
  { code: "BLR", name: "Kempegowda International", city: "Bangalore", country: "India" },
  { code: "MAA", name: "Chennai International", city: "Chennai", country: "India" },
  { code: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose", city: "Kolkata", country: "India" },
  { code: "COK", name: "Cochin International", city: "Kochi", country: "India" },
  { code: "GOI", name: "Goa Dabolim Airport", city: "Goa", country: "India" },
  { code: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa" },
  { code: "JNB", name: "O.R. Tambo International", city: "Johannesburg", country: "South Africa" },
  { code: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya" },
  { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
  { code: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco" },
  { code: "GRU", name: "São Paulo-Guarulhos International", city: "São Paulo", country: "Brazil" },
  { code: "GIG", name: "Rio de Janeiro-Galeão", city: "Rio de Janeiro", country: "Brazil" },
  { code: "EZE", name: "Ministro Pistarini Airport", city: "Buenos Aires", country: "Argentina" },
  { code: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia" },
  { code: "MEX", name: "Mexico City International", city: "Mexico City", country: "Mexico" },
  { code: "CUN", name: "Cancún International", city: "Cancún", country: "Mexico" },
  { code: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
  { code: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
  { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
  { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
  { code: "OSL", name: "Oslo Airport Gardermoen", city: "Oslo", country: "Norway" },
  { code: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "Finland" },
  { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
  { code: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
  { code: "BUD", name: "Budapest Ferenc Liszt", city: "Budapest", country: "Hungary" },
  { code: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "Russia" },
  { code: "DME", name: "Domodedovo International", city: "Moscow", country: "Russia" },
  { code: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel" },
  { code: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia" },
  { code: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia" },
  { code: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica" },
  { code: "PAP", name: "Toussaint Louverture Airport", city: "Port-au-Prince", country: "Haiti" },
];

export const HOTELS_BY_CITY: Record<string, Hotel[]> = {
  London: [
    { id: "lon-1", name: "The Savoy", area: "Strand, Central London", city: "London" },
    { id: "lon-2", name: "The Ritz London", area: "Piccadilly, Mayfair", city: "London" },
    { id: "lon-3", name: "Shangri-La at The Shard", area: "London Bridge", city: "London" },
    { id: "lon-4", name: "Park Plaza Westminster Bridge", area: "Waterloo, South Bank", city: "London" },
    { id: "lon-5", name: "Hilton London Metropole", area: "Paddington, Central London", city: "London" },
    { id: "lon-6", name: "The Langham", area: "Portland Place, Regent's Park", city: "London" },
    { id: "lon-7", name: "InterContinental Park Lane", area: "Mayfair, Central London", city: "London" },
    { id: "lon-8", name: "Premier Inn County Hall", area: "South Bank, Waterloo", city: "London" },
  ],
  Dubai: [
    { id: "dxb-1", name: "Burj Al Arab Jumeirah", area: "Jumeirah Beach", city: "Dubai" },
    { id: "dxb-2", name: "Atlantis The Palm", area: "Palm Jumeirah", city: "Dubai" },
    { id: "dxb-3", name: "Armani Hotel Dubai", area: "Downtown Dubai, Burj Khalifa", city: "Dubai" },
    { id: "dxb-4", name: "JW Marriott Marquis Dubai", area: "Business Bay", city: "Dubai" },
    { id: "dxb-5", name: "Raffles Dubai", area: "Wafi City, Oud Metha", city: "Dubai" },
    { id: "dxb-6", name: "Four Seasons Resort DIFC", area: "DIFC, Financial Centre", city: "Dubai" },
    { id: "dxb-7", name: "Hyatt Regency Dubai", area: "Deira Corniche", city: "Dubai" },
    { id: "dxb-8", name: "Jumeirah Beach Hotel", area: "Jumeirah Beach Residence", city: "Dubai" },
  ],
  "New York": [
    { id: "nyc-1", name: "The Plaza Hotel", area: "5th Avenue, Midtown Manhattan", city: "New York" },
    { id: "nyc-2", name: "Four Seasons New York", area: "57th Street, Midtown", city: "New York" },
    { id: "nyc-3", name: "The Ritz-Carlton New York", area: "Central Park South", city: "New York" },
    { id: "nyc-4", name: "Marriott Marquis Times Square", area: "Times Square, Midtown", city: "New York" },
    { id: "nyc-5", name: "Hilton New York Midtown", area: "53rd Street, Midtown", city: "New York" },
    { id: "nyc-6", name: "1 Hotel Brooklyn Bridge", area: "Brooklyn Bridge Park", city: "New York" },
    { id: "nyc-7", name: "The Standard High Line", area: "Meatpacking District", city: "New York" },
    { id: "nyc-8", name: "Hyatt Grand Central New York", area: "42nd Street, Midtown", city: "New York" },
  ],
  Paris: [
    { id: "par-1", name: "Hôtel de Crillon", area: "Place de la Concorde, 1st Arr.", city: "Paris" },
    { id: "par-2", name: "The Ritz Paris", area: "Place Vendôme, 1st Arr.", city: "Paris" },
    { id: "par-3", name: "Le Meurice", area: "Rue de Rivoli, 1st Arr.", city: "Paris" },
    { id: "par-4", name: "Hilton Paris Opera", area: "Gare Saint-Lazare, 8th Arr.", city: "Paris" },
    { id: "par-5", name: "Pullman Paris Tour Eiffel", area: "Near Eiffel Tower, 15th Arr.", city: "Paris" },
    { id: "par-6", name: "Marriott Champs-Élysées", area: "Champs-Élysées, 8th Arr.", city: "Paris" },
    { id: "par-7", name: "Hotel Lutetia", area: "Saint-Germain-des-Prés, 6th Arr.", city: "Paris" },
    { id: "par-8", name: "Novotel Paris Les Halles", area: "Les Halles, 1st Arr.", city: "Paris" },
  ],
  Tokyo: [
    { id: "tyo-1", name: "The Peninsula Tokyo", area: "Marunouchi, Chiyoda", city: "Tokyo" },
    { id: "tyo-2", name: "Park Hyatt Tokyo", area: "Shinjuku", city: "Tokyo" },
    { id: "tyo-3", name: "Four Seasons Hotel Tokyo", area: "Otemachi", city: "Tokyo" },
    { id: "tyo-4", name: "Imperial Hotel Tokyo", area: "Hibiya, Chiyoda", city: "Tokyo" },
    { id: "tyo-5", name: "Hilton Tokyo Bay", area: "Tokyo Disney Resort, Urayasu", city: "Tokyo" },
    { id: "tyo-6", name: "Mandarin Oriental Tokyo", area: "Nihonbashi Muromachi", city: "Tokyo" },
    { id: "tyo-7", name: "Grand Hyatt Tokyo", area: "Roppongi Hills, Minato", city: "Tokyo" },
    { id: "tyo-8", name: "Shinjuku Prince Hotel", area: "Shinjuku", city: "Tokyo" },
  ],
  Singapore: [
    { id: "sin-1", name: "Marina Bay Sands", area: "Marina Bay", city: "Singapore" },
    { id: "sin-2", name: "Raffles Singapore", area: "Bras Basah Road", city: "Singapore" },
    { id: "sin-3", name: "Mandarin Oriental Singapore", area: "Marina Square", city: "Singapore" },
    { id: "sin-4", name: "Shangri-La Singapore", area: "Orchard Road", city: "Singapore" },
    { id: "sin-5", name: "Fullerton Hotel Singapore", area: "Fullerton Square", city: "Singapore" },
    { id: "sin-6", name: "Hilton Singapore Orchard", area: "Orchard Road", city: "Singapore" },
    { id: "sin-7", name: "Capella Singapore", area: "Sentosa Island", city: "Singapore" },
    { id: "sin-8", name: "Swissôtel The Stamford", area: "Raffles City", city: "Singapore" },
  ],
  Sydney: [
    { id: "syd-1", name: "Park Hyatt Sydney", area: "The Rocks, Sydney Harbour", city: "Sydney" },
    { id: "syd-2", name: "Shangri-La Sydney", area: "Cumberland Street, The Rocks", city: "Sydney" },
    { id: "syd-3", name: "Hilton Sydney", area: "George Street, CBD", city: "Sydney" },
    { id: "syd-4", name: "InterContinental Sydney", area: "Macquarie Street, CBD", city: "Sydney" },
    { id: "syd-5", name: "The Langham Sydney", area: "Kent Street, The Rocks", city: "Sydney" },
    { id: "syd-6", name: "Pullman Quay Grand Sydney", area: "Sydney Cove", city: "Sydney" },
  ],
  Mumbai: [
    { id: "bom-1", name: "The Taj Mahal Palace", area: "Apollo Bunder, Colaba", city: "Mumbai" },
    { id: "bom-2", name: "The Oberoi Mumbai", area: "Nariman Point, Marine Drive", city: "Mumbai" },
    { id: "bom-3", name: "Trident Nariman Point", area: "Nariman Point", city: "Mumbai" },
    { id: "bom-4", name: "Four Seasons Hotel Mumbai", area: "Worli", city: "Mumbai" },
    { id: "bom-5", name: "Grand Hyatt Mumbai", area: "BKC, Bandra East", city: "Mumbai" },
    { id: "bom-6", name: "ITC Maratha Mumbai", area: "Andheri East, near Airport", city: "Mumbai" },
    { id: "bom-7", name: "JW Marriott Mumbai Juhu", area: "Juhu Beach", city: "Mumbai" },
    { id: "bom-8", name: "The Leela Mumbai", area: "Andheri East, near Airport", city: "Mumbai" },
  ],
  Istanbul: [
    { id: "ist-1", name: "Çırağan Palace Kempinski", area: "Besiktas, Bosphorus", city: "Istanbul" },
    { id: "ist-2", name: "Four Seasons Bosphorus", area: "Beşiktaş", city: "Istanbul" },
    { id: "ist-3", name: "The Ritz-Carlton Istanbul", area: "Dolmabahçe, Beşiktaş", city: "Istanbul" },
    { id: "ist-4", name: "Hilton Istanbul Bosphorus", area: "Harbiye, Şişli", city: "Istanbul" },
    { id: "ist-5", name: "InterContinental Istanbul", area: "Taksim Square", city: "Istanbul" },
    { id: "ist-6", name: "Swissôtel The Bosphorus", area: "Maçka, Beşiktaş", city: "Istanbul" },
  ],
  Bangkok: [
    { id: "bkk-1", name: "Mandarin Oriental Bangkok", area: "Riverside, Bang Rak", city: "Bangkok" },
    { id: "bkk-2", name: "The Siam Hotel", area: "Riverside, Dusit", city: "Bangkok" },
    { id: "bkk-3", name: "Shangri-La Bangkok", area: "Riverside, Bang Rak", city: "Bangkok" },
    { id: "bkk-4", name: "Hilton Bangkok Millennium", area: "Sukhumvit 18, Khlong Toei", city: "Bangkok" },
    { id: "bkk-5", name: "Grand Hyatt Erawan Bangkok", area: "Ratchadamri, Pathum Wan", city: "Bangkok" },
    { id: "bkk-6", name: "InterContinental Bangkok", area: "Ploenchit, Pathum Wan", city: "Bangkok" },
  ],
  Amsterdam: [
    { id: "ams-1", name: "Hotel Pulitzer Amsterdam", area: "Prinsengracht, Canal Ring", city: "Amsterdam" },
    { id: "ams-2", name: "Conservatorium Hotel", area: "Van Baerlestraat, Museumplein", city: "Amsterdam" },
    { id: "ams-3", name: "Hilton Amsterdam", area: "Apollolaan, Zuid", city: "Amsterdam" },
    { id: "ams-4", name: "InterContinental Amstel", area: "Professor Tulpplein, Riverside", city: "Amsterdam" },
    { id: "ams-5", name: "W Amsterdam", area: "Spuistraat, Central", city: "Amsterdam" },
  ],
  "Cape Town": [
    { id: "cpt-1", name: "One&Only Cape Town", area: "V&A Waterfront", city: "Cape Town" },
    { id: "cpt-2", name: "The Silo Hotel", area: "V&A Waterfront", city: "Cape Town" },
    { id: "cpt-3", name: "Cape Grace Hotel", area: "V&A Waterfront", city: "Cape Town" },
    { id: "cpt-4", name: "Hilton Cape Town City Centre", area: "Buitengracht Street", city: "Cape Town" },
    { id: "cpt-5", name: "Radisson Blu Hotel Waterfront", area: "Granger Bay", city: "Cape Town" },
  ],
};

export function getHotelsForCity(city: string): Hotel[] {
  return HOTELS_BY_CITY[city] || [];
}

export function getHotelsForAirport(airportCode: string): Hotel[] {
  const airport = AIRPORT_LIST.find((a) => a.code === airportCode);
  if (!airport) return [];
  return getHotelsForCity(airport.city);
}

export const AIRPORT_DATALIST = AIRPORT_LIST.map((a) => ({
  label: `${a.code} - ${a.name}, ${a.city}, ${a.country}`,
  value: `${a.code} - ${a.name}, ${a.city}`,
  code: a.code,
  city: a.city,
}));
